CREATE TABLE clientes (
    id_cliente NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    email VARCHAR2(100),
    telefono VARCHAR2(20),
    direccion VARCHAR2(150)
);

CREATE TABLE usuarios (
    id_usuario NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    email VARCHAR2(100),
    rol VARCHAR2(50),
    password_hash VARCHAR2(255)
);

CREATE TABLE productos (
    id_producto NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    marca VARCHAR2(50),
    modelo VARCHAR2(50),
    talla NUMBER(4,1),
    color VARCHAR2(50),
    precio NUMBER(8,2),
    stock NUMBER,
    categoria VARCHAR2(50)
);

CREATE TABLE ventas (
    id_venta NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente NUMBER,
    id_usuario NUMBER,
    fecha DATE DEFAULT SYSDATE,
    estado VARCHAR2(30),
    total NUMBER(10,2),

    CONSTRAINT fk_cliente
    FOREIGN KEY (id_cliente)
    REFERENCES clientes(id_cliente),

    CONSTRAINT fk_usuario
    FOREIGN KEY (id_usuario)
    REFERENCES usuarios(id_usuario)
);

CREATE TABLE detalle_venta (
    id_detalle NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_venta NUMBER,
    id_producto NUMBER,
    cantidad NUMBER,
    precio_unitario NUMBER(8,2),

    CONSTRAINT fk_venta
    FOREIGN KEY (id_venta)
    REFERENCES ventas(id_venta),

    CONSTRAINT fk_producto
    FOREIGN KEY (id_producto)
    REFERENCES productos(id_producto)
);